### ISSUE TITLE
'c' flag for :substitute command is broken

### ISSUE THREAD

**Issue by jonsmithers** [emilyst/match-count-statusline#1]
This plugin seems to interrupt the `:substitute` command when using the `c` flag.

I'm replicating this with the following "minimal vimrc":

```bash
vim -Nu NONE \
  -c 'set rtp+=~/.vim/plugged/match-count-statusline/' \
  -c 'set rtp+=~/.vim/plugged/match-count-statusline/after/' \
  -c 'runtime! plugin/*.vim' \
  -c 'set statusline=%<%f\ %h%m%{MatchCountStatusline()}%r%=%-14.(%l,%c%V%)\ %P' \
  -c 'set laststatus=2'
```

#### steps to reproduce

1. Start with a document containing a sample match multiple times
2. Run `:%s/sample match/replacement/gc`

#### expected result

- You can press 'y' repeatedly, until all matches are replaced.

#### actual result

- The substitute command stops after 'y' is pressed once.
- Only the first match is replaced.

**Comment by emilyst** [comment]
Ah, wow, I'm so sorry I missed this one! I got no notifications. Weird. Lemme see if I can fix it soon.

**Comment by emilyst** [comment]
Can you confirm this is fixed in https://github.com/emilyst/match-count-statusline/commit/d2beac48e18aca2f454d06063973e1a7dd2f228e?

**Comment by jonsmithers** [comment]
It works. Thank you!
